apiVersion: v1
kind: ReplicationController
metadata:
  name: nlb-console-admin
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: console-admin
    spec:
      containers:
      - name: console-admin
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080